<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FreshViewer</RootNamespace>
    <AssemblyName>FreshViewer</AssemblyName>
    <Version>0.9.0-alpha</Version>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="Effects\LiquidGlass\Assets\**" />
    <AvaloniaResource Include="Styles\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.3" />
    <PackageReference Include="Avalonia.Skia" Version="11.3.3" />
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.8.2" />
    <PackageReference Include="MetadataExtractor" Version="2.8.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.3" />
  </ItemGroup>
</Project>
